---
# Ansible Inventory
# This will be dynamically populated by Terraform outputs or GitHub Actions

all:
  children:
    ubuntu_vms:
      hosts:
        test-vm:
          ansible_host: 74.249.14.98  # Replace with Terraform output or use dynamic inventory
          ansible_user: azureuser
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3
          
          # VM-specific variables
          vm_environment: test
          vm_purpose: dr-testing
